### ISSUE TITLE
Update why dpm

### ISSUE THREAD

**Issue by joebowbeer** [bavarianbidi/kubectl-dpm#8]
[why dpm](https://github.com/bavarianbidi/kubectl-dpm#why-dpm) states:

> As of now, kubectl in v1.30 didn't got released yet. To get familiar with custom debug profiles, this wrapper got created.

However, kubectl 1.30.1 has been released.

It looks like the canned profiles and the custom profiles can be combined in one kubectl debug invocation, in which case the custom profile is merged with the base profile.

Demo: https://github.com/joebowbeer/kubectl-debug-demo

**Comment by bavarianbidi** [comment]
Hey @joebowbeer, thanks for raising this issue.

i've just re-implemented `kubectl-dpm` to be "just" a wrapper for the alpha feature in `>= kubectl v1.30.0`.

As long as https://github.com/kubernetes/enhancements/issues/3104 is still in development (and support for plugins isn't implemented yet) i still see a need for `dpm`.
